---
resources:
- name: cfops-github
  type: git
  source:
    uri: git@github.com:EngineerBetter/cfops-docker.git
    branch: master
    private_key: ((github_private_key))

- name: aws-cli-git
  type: git
  source:
    uri: https://github.com/aws/aws-cli.git
    tag_filter: 1.*.*

- name: cfops-image
  type: docker-image
  source:
    username: ((dockerhub_user))
    password: ((dockerhub_password))
    repository: engineerbetter/cf-ops

- name: base-image
  type: docker-image
  source:
    repository: alpine

- name: terraform-github-release
  type: github-release
  source:
    owner: hashicorp
    repository: terraform
    access_token: ((github_access_token)) # Avoids rate limits

- name: cf-cli-github-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: cli
    access_token: ((github_access_token)) # Avoids rate limits
    tag_filter: v?([^v].*)$

- name: jq-github-release
  type: github-release
  source:
    owner: stedolan
    repository: jq
    access_token: ((github_access_token)) # Avoids rate limits

- name: om-github-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: om
    access_token: ((github_access_token)) # Avoids rate limits

- name: concourse-github-release
  type: github-release
  source:
    owner: concourse
    repository: concourse
    access_token: ((github_access_token)) # Avoids rate limits

- name: bbl-github-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: bosh-bootloader
    access_token: ((github_access_token)) # Avoids rate limits

- name: yq-github-release
  type: github-release
  source:
    owner: mikefarah
    repository: yq
    access_token: ((github_access_token)) # Avoids rate limits

- name: cf-uaac-github-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: cf-uaac
    access_token: ((github_access_token)) # Avoids rate limits

- name: credhub-cli-github-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: credhub-cli
    access_token: ((github_access_token)) # Avoids rate limits

- name: certstrap-github-release
  type: github-release
  source:
    owner: square
    repository: certstrap
    access_token: ((github_access_token))

- name: kubernetes-github-release
  type: github-release
  source:
    owner: kubernetes
    repository: kubernetes
    access_token: ((github_access_token))

- name: bosh-cli-release
  type: github-release
  source:
    owner: cloudfoundry
    repository: bosh-cli
    access_token: ((github_access_token))

- name: cfops-docker-tag
  type: semver
  source:
    driver: s3
    key: docker-tag
    <<: &aws_creds
      bucket: cf-ops-pipeline
      access_key_id: ((aws_access_key_id))
      secret_access_key: ((aws_secret_access_key))
      region_name: eu-west-1

- name: terraform-s3-release
  type: s3
  source:
    versioned_file: terraform/terraform
    <<: *aws_creds

- name: cf-cli-s3-release
  type: s3
  source:
    versioned_file: cf/cf
    <<: *aws_creds

- name: kubectl-s3-release
  type: s3
  source:
    versioned_file: kubectl/kubectl
    <<: *aws_creds

- name: aws-cli-s3-release
  type: s3
  source:
    versioned_file: aws-cli/awscli-bundle.zip
    <<: *aws_creds

jobs:
- name: set-pipeline
  serial: true
  plan:
  - get: cfops-github
    trigger: true
  - set_pipeline: cfops-docker
    file: cfops-github/ci/pipeline.yml

- name: get-kubectl
  public: true
  serial: true
  plan:
  - get: kubernetes-github-release
    trigger: true
  - task: download
    config:
      platform: linux
      inputs:
      - name: kubernetes-github-release
      outputs:
      - name: kubectl
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: ash
        args:
        - -xc
        - |
          set -euo pipefail
          version=$(cat kubernetes-github-release/version)
          url="https://dl.k8s.io/v${version}/kubernetes-client-linux-amd64.tar.gz"
          wget -O kubernetes-client.tar.gz "$url"
          tar -xf kubernetes-client.tar.gz
          cp kubernetes/client/bin/kubectl kubectl/
  - put: kubectl-s3-release
    params: {file: kubectl/kubectl}

- name: get-terraform
  public: true
  serial: true
  plan:
  - get: terraform-github-release
    trigger: true
  - task: download
    config:
      platform: linux
      inputs:
      - name: terraform-github-release
      outputs:
      - name: terraform
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: ash
        args:
        - -c
        - |
          set -euo pipefail
          version=$(cat terraform-github-release/version)
          url="https://releases.hashicorp.com/terraform/${version}/terraform_${version}_linux_amd64.zip"
          wget -O terraform.zip "$url"
          unzip -d terraform terraform.zip
  - put: terraform-s3-release
    params: {file: terraform/terraform}

- name: get-cf-cli
  public: true
  serial: true
  plan:
  - get: cf-cli-github-release
    trigger: true
  - task: download
    config:
      platform: linux
      inputs:
      - name: cf-cli-github-release
      outputs:
      - name: cf
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: ash
        args:
        - -c
        - |
          set -euo pipefail
          version=$(cat cf-cli-github-release/version)
          url="https://cli.run.pivotal.io/stable?release=linux64-binary&version=${version}&source=github-rel"
          wget -O cli.tgz "$url"
          tar -C cf -xzf cli.tgz
  - put: cf-cli-s3-release
    params: {file: cf/cf}

- name: get-aws-cli
  public: true
  serial: true
  plan:
  - get: aws-cli-git
    trigger: true
  - task: download
    config:
      platform: linux
      outputs:
      - name: aws-cli
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: ash
        args:
        - -c
        - |
          set -euo pipefail
          url="https://s3.amazonaws.com/aws-cli/awscli-bundle.zip"
          wget -O aws-cli/awscli-bundle.zip "$url"
  - put: aws-cli-s3-release
    params: {file: aws-cli/awscli-bundle.zip}

- name: build-cfops-image
  public: true
  serial: true
  plan:
  - in_parallel:
    - get: cfops-docker-tag
      params: {bump: minor}
    # Download Dockerfile
    - get: cfops-github
      passed:
      - set-pipeline
      trigger: true
    # Trigger on base image updates
    - get: base-image
      trigger: true
    # Download dependancies
    - get: terraform-s3-release
      trigger: true
      passed: [get-terraform]
    - get: cf-cli-s3-release
      trigger: true
      passed: [get-cf-cli]
    - get: jq-github-release
      trigger: true
      params:
        globs: [jq-linux64]
    - get: om-github-release
      trigger: true
      params:
        globs: [om-linux-*.tar.gz]
    - get: concourse-github-release
      trigger: true
      params:
        globs: [fly-*-linux-amd64.tgz]
    - get: bosh-cli-release
      trigger: true
      params:
        globs: [bosh-cli-*-linux-amd64]
    - get: bbl-github-release
      trigger: true
      params:
        globs: [bbl-v*_linux_x86-64]
    - get: yq-github-release
      trigger: true
      params:
        globs: [yq_linux_amd64]
    - get: aws-cli-s3-release
      trigger: true
      passed: [get-aws-cli]
    - get: cf-uaac-github-release
      trigger: true
    - get: credhub-cli-github-release
      trigger: true
      params:
        globs: [credhub-linux-*.tgz]
    - get: certstrap-github-release
      trigger: true
      params:
        globs: [certstrap-v*-linux-amd64]
    - get: kubectl-s3-release
      trigger: true
      passed: [get-kubectl]
  # Copy dependencies
  - task: copy
    config:
      platform: linux
      inputs:
      - name: cfops-github
      - name: terraform-s3-release
      - name: cf-cli-s3-release
      - name: jq-github-release
      - name: om-github-release
      - name: concourse-github-release
      - name: bosh-cli-release
      - name: bbl-github-release
      - name: yq-github-release
      - name: aws-cli-s3-release
      - name: credhub-cli-github-release
      - name: certstrap-github-release
      - name: kubectl-s3-release
      outputs:
      - name: builddir
      image_resource:
        type: docker-image
        source: {repository: busybox}
      run:
        path: ash
        args:
          - -xeuc
          - |
            cp -r cfops-github/. builddir/
            cp terraform-s3-release/terraform builddir/terraform
            cp cf-cli-s3-release/cf builddir/cf
            cp jq-github-release/jq-linux64 builddir/jq
            tar xzf om-github-release/om-linux-*.tar.gz -C builddir
            tar xzf concourse-github-release/fly-*-linux-amd64.tgz -C builddir/
            tar xzf credhub-cli-github-release/credhub-linux-*.tgz -C builddir
            cp bosh-cli-release/bosh-cli-*-linux-amd64 builddir/bosh
            cp bbl-github-release/bbl-v*_linux_x86-64 builddir/bbl
            cp yq-github-release/yq_linux_amd64 builddir/yq
            cp certstrap-github-release/certstrap-v*-linux-amd64 builddir/certstrap
            cp aws-cli-s3-release/awscli-bundle.zip builddir/awscli-bundle.zip
            cp kubectl-s3-release/kubectl builddir/kubectl

            wget https://storage.googleapis.com/shellcheck/shellcheck-stable.linux.x86_64.tar.xz
            tar xJf shellcheck-stable.linux.x86_64.tar.xz
            cp shellcheck-stable/shellcheck builddir/

  - put: cfops-image
    params:
      build: builddir
      tag: cfops-docker-tag/version
      tag_as_latest: true
  - put: cfops-github
    params:
      repository: cfops-github
      tag: cfops-docker-tag/version
      only_tag: true
  - put: cfops-docker-tag
    params: {file: cfops-docker-tag/version}
